### ISSUE TITLE
aleph.netty exception in luminus

### ISSUE THREAD

**Issue by vinurs** [clj-commons/aleph#504]
i use luminus to write a rest server,
create a project
```
lein new luminus sy-api-server +reitit +aleph +postgres +swagger +service +auth +auth-jwe +oauth
```
then i use emacs cider 
```
cider-jack-in
```

> [nREPL] Starting server via /usr/local/bin/lein update-in :dependencies conj \[nrepl\ \"0.6.0\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.22.0-SNAPSHOT\"\] -- repl :headless :host localhost...

then i execute
```
(mount/start)
(mount/stop)
```
it outputs the exception
> 2019-04-11 15:33:46,355 [nRepl-session-e3c6779c-d48b-40b2-9b34-84f4739819ea] INFO  sy-api-server.env - 
-=[sy-api-server started successfully using the development profile]=- 
2019-04-11 15:33:46,520 [nRepl-session-e3c6779c-d48b-40b2-9b34-84f4739819ea] INFO  luminus.http-server - starting HTTP server on port 3000 
2019-04-11 15:33:46,869 [nRepl-session-e3c6779c-d48b-40b2-9b34-84f4739819ea] INFO  sy-api-server.nrepl - starting nREPL server on port 7000 
2019-04-11 15:33:46,872 [nRepl-session-e3c6779c-d48b-40b2-9b34-84f4739819ea] WARN  sy-api-server.db.core - database connection URL was not found, please set :database-url in your config, e.g: dev-config.edn 
2019-04-11 15:33:50,296 [nRepl-session-e3c6779c-d48b-40b2-9b34-84f4739819ea] INFO  sy-api-server.nrepl - nREPL server stopped 
2019-04-11 15:33:50,301 [nRepl-session-e3c6779c-d48b-40b2-9b34-84f4739819ea] INFO  luminus.http-server - HTTP server stopped 
2019-04-11 15:33:50,302 [nRepl-session-e3c6779c-d48b-40b2-9b34-84f4739819ea] INFO  sy-api-server.env - 
-=[sy-api-server has shut down successfully]=- 
2019-04-11 15:33:52,521 [globalEventExecutor-2-1] WARN  i.n.util.concurrent.DefaultPromise - An exception was thrown by aleph.netty$wrap_future$reify__24460.operationComplete() 
java.lang.ExceptionInInitializerError: null
	at manifold.deferred.Deferred.success(deferred.clj:398)
	at manifold.deferred$success_BANG_.invokeStatic(deferred.clj:243)
	at manifold.deferred$success_BANG_.invoke(deferred.clj:240)
	at aleph.netty$wrap_future$reify__24460.operationComplete(netty.clj:199)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:94)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup$1.operationComplete(MultithreadEventExecutorGroup.java:117)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:248)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: clojure/lang/PersistentArrayMap
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at clojure.lang.RT.classForName(RT.java:2207)
	at clojure.lang.RT.classForName(RT.java:2216)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:324)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1322)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:853)
	at clojure.lang.LispReader.read(LispReader.java:285)
	at clojure.lang.LispReader.read(LispReader.java:220)
	at clojure.lang.LispReader.access$200(LispReader.java:41)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:954)
	at clojure.lang.LispReader.read(LispReader.java:285)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1398)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1243)
	at clojure.lang.LispReader.read(LispReader.java:285)
	at clojure.lang.LispReader.read(LispReader.java:220)
	at clojure.lang.LispReader.access$200(LispReader.java:41)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1301)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:853)
	at clojure.lang.LispReader.read(LispReader.java:285)
	at clojure.lang.LispReader.read(LispReader.java:216)
	at clojure.lang.LispReader.read(LispReader.java:205)
	at clojure.lang.RT.readString(RT.java:1874)
	at clojure.lang.RT.readString(RT.java:1869)
	at manifold.deferred.Deferred$fn__21189.<clinit>(deferred.clj:398)
	... 16 common frames omitted

**Comment by gsnewmark** [comment]
It's [fixed since Aleph 0.4.7-alpha5](https://github.com/ztellman/aleph/pull/425), but Luminus uses [older Aleph version 0.4.6](https://github.com/luminus-framework/luminus-aleph/blob/67cdd0f09350b77e49dd4b8c5107e282a5d0cfba/project.clj#L8).

**Comment by vinurs** [comment]
👌，thanks

**Comment by yogthos** [comment]
@gsnewmark is 0.4.7-alpha5 considered stable, if so I can update Luminus to use it.

**Comment by gsnewmark** [comment]
@yogthos I can't say for sure as I'm not actively using Aleph right now, but previous alphas tended to be quite stable. It's better to ask @kachayev @ztellman about it.

**Comment by yogthos** [comment]
Any chance I could get a pr [here](https://github.com/luminus-framework/luminus-aleph/blob/master/project.clj) to bump up the version when it's the right time to update? :)

**Comment by arnaudgeiser** [comment]
As requested by Dmitri, I opened a PR on `luminus-framework`, I guess this issue can be closed.
