### ISSUE TITLE
"Error in stream handler" trying to run TCP example

### ISSUE THREAD

**Issue by mwiederhold** [clj-commons/aleph#570]
Hi all,

I am looking into aleph because I am writing a client for a TCP service. I have copy-pasted the example code for TCP (from aleph.examples 0.4.6) up to and including this line `(def c @(client "localhost" 10000))`. I then jack-in to a Lein repl via Calva on VS Code and evaluate the following expression: `@(s/put! c 1)`. Instead of `true` it returns `nil` and I see the following stacktrace in the repl:

```
Sep 13, 2021 9:32:39 AM clojure.tools.logging$eval156$fn__159 invoke
SCHWERWIEGEND: error in stream handler
java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
        at gloss.data.primitives$reify__952.write_bytes(primitives.clj:151)
        at gloss.data.bytes$wrap_finite_block$reify__627.write_bytes(bytes.clj:90)
        at gloss.core.structure$compile_frame$reify__1226.write_bytes(structure.clj:125)
        at gloss.io$encode.invokeStatic(io.clj:44)
        at gloss.io$encode.invoke(io.clj:40)
        at tarefas_test.core$wrap_duplex_stream$fn__189.invoke(core.clj:22)
        at manifold.stream$map$fn__2730.invoke(stream.clj:620)
        at manifold.stream.Callback.put(stream.clj:454)
        at manifold.stream.graph$async_send.invokeStatic(graph.clj:81)
        at manifold.stream.graph$async_send.invoke(graph.clj:77)
        at manifold.stream.graph$async_connect$this__2125.invoke(graph.clj:210)
        at manifold.stream.graph$async_connect$this__2125$fn__2126$fn__2127.invoke(graph.clj:191)
        at clojure.core$trampoline.invokeStatic(core.clj:6230)
        at clojure.core$trampoline.invoke(core.clj:6219)
        at manifold.stream.graph$async_connect$this__2125$fn__2126.invoke(graph.clj:191)
        at manifold.deferred.Listener.onSuccess(deferred.clj:219)
        at manifold.deferred.Deferred$fn__1593.invoke(deferred.clj:400)
        at manifold.deferred.Deferred.success(deferred.clj:400)
        at manifold.deferred$success_BANG_.invokeStatic(deferred.clj:245)
        at manifold.deferred$success_BANG_.invoke(deferred.clj:240)
        at manifold.stream.default.Stream$fn__2264.invoke(default.clj:178)
        at manifold.stream.default.Stream.put(default.clj:164)
        at manifold.stream.default.Stream.put(default.clj:200)
        at manifold.stream.SplicedStream.put(stream.clj:403)
        at tarefas_test.core$eval5448.invokeStatic(form-init3992102404283288161.clj:21)
        at tarefas_test.core$eval5448.invoke(form-init3992102404283288161.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7025)
        at clojure.core$eval.invokeStatic(core.clj:3206)
        at clojure.core$eval.invoke(core.clj:3202)
        at nrepl.middleware.interruptible_eval$evaluate$fn__975$fn__976.invoke(interruptible_eval.clj:87)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:657)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at nrepl.middleware.interruptible_eval$evaluate$fn__975.invoke(interruptible_eval.clj:87)
        at clojure.main$repl$read_eval_print__8572$fn__8575.invoke(main.clj:243)
        at clojure.main$repl$read_eval_print__8572.invoke(main.clj:243)
        at clojure.main$repl$fn__8581.invoke(main.clj:261)
        at clojure.main$repl.invokeStatic(main.clj:261)
        at clojure.main$repl.doInvoke(main.clj:177)
        at clojure.lang.RestFn.invoke(RestFn.java:1523)
        at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:84)
        at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
        at nrepl.middleware.interruptible_eval$interruptible_eval$fn__1006$fn__1010.invoke(interruptible_eval.clj:152)
        at clojure.lang.AFn.run(AFn.java:22)
        at nrepl.middleware.session$session_exec$main_loop__1073$fn__1077.invoke(session.clj:202)
        at nrepl.middleware.session$session_exec$main_loop__1073.invoke(session.clj:201)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:748)
```

(Obviously, a subsequent `@(s/take c)` evaluates to `nil`). This is my project.clj:
```clojure
(defproject tarefas-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[aleph "0.4.6"]
                 [compojure "1.6.1"]
                 [gloss "0.2.6"]
                 [manifold "0.1.9"]
                 [org.clojure/clojure "1.9.0"]
                 [org.clojure/core.async "0.4.474"]]
  :main ^:skip-aot tarefas-test.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

This is the output of `java -version` on my Pop!_OS 21.04 Virtual Machine:
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

I am not experienced enough with Clojure yet to debug this issue. Maybe you can point me in the right direction?

Btw, I get a totally different error when trying with Java 11, I can post that also.

**Comment by KingMob** [comment]
@mwiederhold I can't seem to replicate this error. The TCP example works for me under Java 1.8 and 16, in a local REPL, or connecting to a remote nREPL, in both Calva and Cursive.

Is there a complete repo we could look at, and maybe a sequence of commands you used to set it up? 

NoSuchMethodErrors typically result from discrepancies between libs at compile and run time, and issues like differing dependencies in their classpaths. One possible offender is messing with uberjars and using them as a dependency by accident. You may also want to add `:pedantic? :warn` to your project.clj and make sure your deps are what you think and not conflicting.

**Comment by mwiederhold** [comment]
@KingMob, Thank you for looking into this issue! Your reply made me suspicious that the issue was with my use of Calva. Indeed, if I simply run a `lein repl`on the command line, everything is fine. (I will keep that in mind next time I have a problem).

I will try to find out what the problem is with Calva and add that here if someone is interested. But this is definitely not an issue with aleph.
